netbox_dhcp/urls.py
from django.urls import include, path

from utilities.urls import get_model_urls

# +
# Import views so the register_model_view is run. This is required for the
# URLs to be set up properly with get_model_urls().
# -
from .views import *  # noqa: F401

app_name = "netbox_dhcp"

urlpatterns = (
    path(
        "clientclasses/",
        include(get_model_urls("netbox_dhcp", "clientclass", detail=False)),
    ),
    path(
        "clientclasses/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "clientclass")),
    ),
    path(
        "ddns/",
        include(get_model_urls("netbox_dhcp", "ddns", detail=False)),
    ),
    path(
        "ddns/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "ddns")),
    ),
    path(
        "hostreservations/",
        include(get_model_urls("netbox_dhcp", "hostreservation", detail=False)),
    ),
    path(
        "hostreservations/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "hostreservation")),
    ),
    path(
        "options/",
        include(get_model_urls("netbox_dhcp", "option", detail=False)),
    ),
    path(
        "options/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "option")),
    ),
    path(
        "optiondefinitions/",
        include(get_model_urls("netbox_dhcp", "optiondefinition", detail=False)),
    ),
    path(
        "optiondefinitions/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "optiondefinition")),
    ),
    path(
        "dhcpclusters/",
        include(get_model_urls("netbox_dhcp", "dhcpcluster", detail=False)),
    ),
    path(
        "dhcpclusters/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "dhcpcluster")),
    ),
    path(
        "dhcpservers/",
        include(get_model_urls("netbox_dhcp", "dhcpserver", detail=False)),
    ),
    path(
        "dhcpservers/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "dhcpserver")),
    ),
    path(
        "pdpools/",
        include(get_model_urls("netbox_dhcp", "pdpool", detail=False)),
    ),
    path(
        "pdpools/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "pdpool")),
    ),
    path(
        "pools/",
        include(get_model_urls("netbox_dhcp", "pool", detail=False)),
    ),
    path(
        "pools/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "pool")),
    ),
    path(
        "sharednetworks/",
        include(get_model_urls("netbox_dhcp", "sharednetwork", detail=False)),
    ),
    path(
        "sharednetworks/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "sharednetwork")),
    ),
    path(
        "subnets/",
        include(get_model_urls("netbox_dhcp", "subnet", detail=False)),
    ),
    path(
        "subnets/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "subnet")),
    ),
)

netbox_dhcp/models/dhcp_cluster.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from netbox.models import PrimaryModel
from netbox.search import SearchIndex, register_search

from netbox_dhcp.choices import DHCPClusterStatusChoices

from .mixins import (
    NetBoxDHCPModelMixin,
)

__all__ = (
    "DHCPCluster",
    "DHCPClusterIndex",
)


class DHCPCluster(NetBoxDHCPModelMixin, PrimaryModel):
    class Meta:
        verbose_name = _("DHCP Cluster")
        verbose_name_plural = _("DHCP Clusters")

        ordering = ("name",)

    clone_fields = (
        "name",
        "description",
        "status",
    )

    status = models.CharField(
        verbose_name=_("Status"),
        max_length=50,
        choices=DHCPClusterStatusChoices,
        default=DHCPClusterStatusChoices.STATUS_ACTIVE,
        blank=True,
    )

    def get_status_color(self):
        return DHCPClusterStatusChoices.colors.get(self.status)


@register_search
class DHCPClusterIndex(SearchIndex):
    model = DHCPCluster

    fields = (
        ("name", 100),
        ("description", 200),
    )

netbox_dhcp/models/option.py
import re

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.exceptions import ValidationError, ObjectDoesNotExist

from netbox.models import PrimaryModel
from netbox.search import SearchIndex, register_search

from netbox_dhcp.choices import OptionTypeChoices, OptionSendChoices
from netbox_dhcp.validators import validate_data

from .mixins import ClientClassModelMixin

__all__ = (
    "Option",
    "OptionIndex",
)


class Option(
    ClientClassModelMixin,
    PrimaryModel,
):
    class Meta:
        verbose_name = _("Option")
        verbose_name_plural = _("Options")

        ordering = (
            "definition__space",
            "definition__code",
            "definition__name",
            "weight",
        )

    definition = models.ForeignKey(
        verbose_name=_("Option Definition"),
        to="OptionDefinition",
        related_name="options",
        on_delete=models.PROTECT,
        null=False,
    )
    assigned_object_type = models.ForeignKey(
        to="contenttypes.ContentType",
        on_delete=models.PROTECT,
        related_name="+",
    )
    assigned_object_id = models.PositiveBigIntegerField()
    assigned_object = GenericForeignKey(
        ct_field="assigned_object_type",
        fk_field="assigned_object_id",
    )
    data = models.CharField(
        verbose_name=_("Option Data"),
        null=False,
        blank=True,
    )
    csv_format = models.BooleanField(
        verbose_name=_("CSV Format"),
        null=True,
        blank=True,
    )
    send_option = models.CharField(
        verbose_name=_("Send Option"),
        choices=OptionSendChoices,
        null=True,
        blank=True,
    )
    weight = models.PositiveSmallIntegerField(
        verbose_name=_("Weight"),
        default=100,
    )

    def __str__(self):
        return f"{self.definition}"

    @property
    def family(self):
        return self.definition.family

    def get_family_display(self):
        return self.definition.get_family_display()

    def clean(self):
        super().clean()

        try:
            definition = self.definition
        except ObjectDoesNotExist:
            raise ValidationError({"definition": _("Option definition is required")})

        if definition is None:
            raise ValidationError({"definition": _("Option definition is required")})

        if definition.type == OptionTypeChoices.TYPE_BINARY:
            self.csv_format = False

        if definition.type == OptionTypeChoices.TYPE_RECORD:
            data_array = re.split(r"\s*,\s*", self.data)
            record_types = definition.record_types

            if (definition.array and len(record_types) > len(data_array)) or (
                not definition.array and len(record_types) != len(data_array)
            ):
                raise ValidationError(
                    {
                        "data": _(
                            "Lengths of record type list and data elements do not match"
                        )
                    }
                )

            for mapping in zip(data_array, record_types):
                validate_data(*mapping)

            if definition.array:
                for data_field in data_array[len(record_types) :]:
                    validate_data(data_field, record_types[-1])

        elif definition.array:
            data_array = re.split(r"\s*,\s*", self.data)
            for data_field in data_array:
                validate_data(data_field, definition.type)

        else:
            validate_data(self.data, definition.type)


@register_search
class OptionIndex(SearchIndex):
    model = Option

    fields = (("data", 100),)

netbox_dhcp/models/option_definition.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
)

from netbox.models import PrimaryModel
from netbox.search import SearchIndex, register_search
from ipam.choices import IPAddressFamilyChoices

from netbox_dhcp.choices import OptionSpaceChoices, OptionTypeChoices
from netbox_dhcp.fields import ChoiceArrayField

__all__ = (
    "OptionDefinition",
    "OptionDefinitionIndex",
)


class OptionDefinition(PrimaryModel):
    class Meta:
        verbose_name = _("Option Definition")
        verbose_name_plural = _("Option Definitions")

        ordering = (
            "space",
            "code",
            "name",
        )

    clone_fields = ("space",)

    name = models.CharField(
        verbose_name=_("Name"),
        max_length=255,
        blank=False,
        null=False,
    )
    family = models.PositiveIntegerField(
        verbose_name=_("Address Family"),
        choices=IPAddressFamilyChoices,
        blank=False,
        null=False,
        default=IPAddressFamilyChoices.FAMILY_4,
    )
    space = models.CharField(
        verbose_name=_("Space"),
        choices=OptionSpaceChoices,
        blank=False,
        null=False,
        default=OptionSpaceChoices.DHCPV4,
    )
    code = models.PositiveIntegerField(
        verbose_name=_("Code"),
        validators=[
            MinValueValidator(1),
            MaxValueValidator(255),
        ],
        blank=False,
        null=False,
    )
    type = models.CharField(
        verbose_name=_("Type"),
        choices=OptionTypeChoices,
        blank=False,
        null=False,
    )
    record_types = ChoiceArrayField(
        base_field=models.CharField(
            choices=OptionTypeChoices,
        ),
        verbose_name=_("Record Types"),
        blank=True,
        null=True,
    )
    encapsulate = models.CharField(
        verbose_name=_("Encapsulate"),
        blank=True,
        null=True,
    )
    array = models.BooleanField(
        verbose_name=_("Array"),
        null=True,
        blank=True,
    )
    standard = models.BooleanField(
        verbose_name=_("Standard Option Type"),
        blank=False,
        null=False,
        default=False,
    )

    dhcp_server = models.ForeignKey(
        verbose_name=_("DHCP Server"),
        to="DHCPServer",
        on_delete=models.CASCADE,
        related_name="option_definitions",
        blank=True,
        null=True,
    )
    client_class = models.ForeignKey(
        verbose_name=_("Client Class"),
        to="ClientClass",
        on_delete=models.CASCADE,
        related_name="option_definitions",
        blank=True,
        null=True,
    )

    def __str__(self):
        return f"{self.space} {self.name} ({self.code})"

    def get_space_color(self):
        return OptionSpaceChoices.colors.get(self.space)


@register_search
class OptionDefinitionIndex(SearchIndex):
    model = OptionDefinition

    fields = (("name", 100),)

netbox_dhcp/forms/client_class.py
from django import forms
from django.utils.translation import gettext_lazy as _

from netbox.forms import (
    PrimaryModelForm,
    PrimaryModelFilterSetForm,
    PrimaryModelImportForm,
    PrimaryModelBulkEditForm,
)
from utilities.forms.fields import TagFilterField
from utilities.forms.rendering import FieldSet
from utilities.forms import BOOLEAN_WITH_BLANK_CHOICES

from netbox_dhcp.models import ClientClass
from .mixins import (
    DHCPServerFormMixin,
    DHCPServerFilterFormMixin,
    DHCPServerImportFormMixin,
    DHCPServerBulkEditFormMixin,
    BOOTPFormMixin,
    BOOTPFilterFormMixin,
    BOOTPImportFormMixin,
    BOOTPBulkEditFormMixin,
    LifetimeFormMixin,
    LifetimeFilterFormMixin,
    LifetimeImportFormMixin,
    LifetimeBulkEditFormMixin,
    NetBoxDHCPBulkEditFormMixin,
    NetBoxDHCPFilterFormMixin,
)


__all__ = (
    "ClientClassForm",
    "ClientClassFilterForm",
    "ClientClassImportForm",
    "ClientClassBulkEditForm",
)


class ClientClassForm(
    DHCPServerFormMixin,
    PrimaryModelForm,
):
    class Meta:
        model = ClientClass

        fields = (
            "name",
            "description",
            "weight",
            *DHCPServerFormMixin.FIELDS,
            "test",
            "template_test",
            "only_in_additional_list",
            *BOOTPFormMixin.FIELDS,
            *LifetimeFormMixin.FIELDS,
            "tags",
        )

        widgets = {
            "test": forms.Textarea(attrs={"rows": 2}),
            "template_test": forms.Textarea(attrs={"rows": 2}),
        }

    fieldsets = (
        FieldSet(
            "name",
            "description",
            "weight",
            *DHCPServerFormMixin.FIELDS,
            "test",
            "template_test",
            "only_in_additional_list",
            name=_("Client Class"),
        ),
        BOOTPFormMixin.FIELDSET,
        LifetimeFormMixin.FIELDSET,
        FieldSet(
            "tags",
            name=_("Tags"),
        ),
    )

    only_in_additional_list = forms.NullBooleanField(
        required=False,
        label=_("Only in additional list"),
        widget=forms.Select(choices=BOOLEAN_WITH_BLANK_CHOICES),
    )


class ClientClassFilterForm(
    NetBoxDHCPFilterFormMixin,
    DHCPServerFilterFormMixin,
    BOOTPFilterFormMixin,
    LifetimeFilterFormMixin,
    PrimaryModelFilterSetForm,
):
    model = ClientClass

    fieldsets = (
        FieldSet(
            "q",
            "filter_id",
            "tag",
            "owner_id",
        ),
        FieldSet(
            "name",
            "description",
            "weight",
            *DHCPServerFilterFormMixin.FIELDS,
            "test",
            "template_test",
            "only_in_additional_list",
            name=_("Client Class"),
        ),
        BOOTPFilterFormMixin.FIELDSET,
        LifetimeFilterFormMixin.FIELDSET,
    )

    weight = forms.IntegerField(
        label=_("Weight"),
        required=False,
    )
    test = forms.CharField(
        required=False,
        label=_("Test"),
    )
    template_test = forms.CharField(
        required=False,
        label=_("Template Test"),
    )
    only_in_additional_list = forms.NullBooleanField(
        required=False,
        label=_("Only in additional list"),
        widget=forms.Select(choices=BOOLEAN_WITH_BLANK_CHOICES),
    )

    tag = TagFilterField(ClientClass)


class ClientClassImportForm(
    DHCPServerImportFormMixin,
    PrimaryModelImportForm,
):
    class Meta:
        model = ClientClass

        fields = (
            "name",
            "description",
            "weight",
            *DHCPServerImportFormMixin.FIELDS,
            "test",
            "template_test",
            "only_in_additional_list",
            *BOOTPImportFormMixin.FIELDS,
            *LifetimeImportFormMixin.FIELDS,
            "comments",
            "tags",
        )


class ClientClassBulkEditForm(
    NetBoxDHCPBulkEditFormMixin,
    DHCPServerBulkEditFormMixin,
    BOOTPBulkEditFormMixin,
    LifetimeBulkEditFormMixin,
    PrimaryModelBulkEditForm,
):
    model = ClientClass

    fieldsets = (
        FieldSet(
            "description",
            "weight",
            *DHCPServerBulkEditFormMixin.FIELDS,
            name=_("Client Class"),
        ),
        FieldSet(
            "test",
            "template_test",
            "only_in_additional_list",
            name=_("Selection"),
        ),
        BOOTPBulkEditFormMixin.FIELDSET,
        LifetimeBulkEditFormMixin.FIELDSET,
    )

    nullable_fields = (
        "description",
        "test",
        "template_test",
        *BOOTPBulkEditFormMixin.NULLABLE_FIELDS,
        *LifetimeBulkEditFormMixin.NULLABLE_FIELDS,
    )

    weight = forms.IntegerField(
        required=False,
        label=_("Weight"),
    )
    test = forms.CharField(
        required=False,
        label=_("Test"),
        widget=forms.Textarea(attrs={"rows": 2}),
    )
    template_test = forms.CharField(
        required=False,
        label=_("Template Test"),
        widget=forms.Textarea(attrs={"rows": 2}),
    )
    only_in_additional_list = forms.NullBooleanField(
        required=False,
        widget=forms.Select(choices=BOOLEAN_WITH_BLANK_CHOICES),
        label=_("Only in additional list"),
    )

netbox_dhcp/templates/netbox_dhcp/dhcpcluster.html
{% extends 'generic/object.html' %}
{% load i18n %}
{% load plugins %}

{% block content %}
    <div class="row">
        <div class="col col-md-6">
            <div class="card">
                <h5 class="card-header">{% trans "DHCP Cluster" %}</h5>
                <table class="table table-hover attr-table">
                    {% include './inc/name_description_fields.html' %}
                    <tr>
                        <th scope="row">{% trans "Status" %}</th>
                        <td>{% badge object.get_status_display bg_color=object.get_status_color %}</td>
                    </tr>
                </table>
            </div>
            {% include 'inc/panels/custom_fields.html' %}
            {% include 'inc/panels/comments.html' %}
            {% plugin_left_page object %}
        </div>
        <div class="col col-md-6">
            {% if object.dhcp_servers.exists %}
            <div class="card">
                <h5 class="card-header">{% trans "DHCP Servers" %}</h5>
                <table class="table table-hover attr-table">
                    {% for dhcp_server in object.dhcp_servers.all %}
                    <tr>
                        <td>{{ dhcp_server|linkify }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            {% endif %}
            {% include 'inc/panels/tags.html' %}
            {% plugin_right_page object %}
        </div>
    </div>
    <div class="row">
        <div class="col col-md-12">
            {% plugin_full_width_page object %}
        </div>
    </div>
{% endblock %}

netbox_dhcp/templates/netbox_dhcp/dhcpserver.html
{% extends './dhcpserver/base.html' %}
{% load i18n %}
{% load netbox_dhcp %}
{% load plugins %}

{% block content %}
    <div class="row">
        <div class="col col-md-6">
            <div class="card">
                <h5 class="card-header">{% trans "DHCP Server" %}</h5>
                <table class="table table-hover attr-table">
                    {% include './inc/name_description_fields.html' %}
                    <tr>
                        <th scope="row">{% trans "Status" %}</th>
                        <td>{% badge object.get_status_display bg_color=object.get_status_color %}</td>
                    </tr>
                    {% if object.dhcp_cluster %}
                        <tr>
                            <th scope="row">{% trans "DHCP Cluster" %}</th>
                            <td>{{ object.dhcp_cluster|linkify|placeholder }}</td>
                        </tr>
                    {% endif %}
                    {% if object.device %}
                        <tr>
                            <th scope="row">{% trans "Device" %}</th>
                            <td>{{ object.device|linkify|placeholder }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{% trans "Interfaces" %}</th>
                            <td>
                                <table>
                                    {% for interface in object.device_interfaces.all %}
                                        <tr><td>{{ interface|linkify }}</td></tr>
                                    {% endfor %}
                                </table>
                            </td>
                        </tr>
                    {% elif object.virtual_machine %}
                        <tr>
                            <th scope="row">{% trans "Virtual Machine" %}</th>
                            <td>{{ object.virtual_machine|linkify|placeholder }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{% trans "Interfaces" %}</th>
                            <td>
                                <table>
                                    {% for interface in object.virtual_machine_interfaces.all %}
                                        <tr><td>{{ interface|linkify }}</td></tr>
                                    {% endfor %}
                                </table>
                            </td>
                        </tr>
                    {% endif %}
                </table>
            </div>
            <div class="card">
                <h5 class="card-header">{% trans "Configuration" %}</h5>
                <table class="table table-hover attr-table">
                    <tr>
                        <th scope="row">{% trans "Server DUID" %}</th>
                        <td>{{ object.server_id|placeholder }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Host Reservation Identifiers" %}</th>
                        <td>
                            {% for identifier in object.host_reservation_identifiers %}
                                {{ identifier }}{{ "&nbsp;" }}
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Echo Client ID" %}</th>
                        <td>{% null_checkmark object.echo_client_id %}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Relay Supplied Options" %}</th>
                        <td>
                            {% for option in object.relay_supplied_options %}
                                {{ option }}{{ "&nbsp;" }}
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Decline Probation Period" %}</th>
                        <td>{{ object.decline_probation_period|placeholder }}</td>
                    </tr>
                </table>
            </div>
            {% include './inc/bootp_card.html' %}
            {% include './inc/lifetime_card.html' %}
            {% include 'inc/panels/custom_fields.html' %}
            {% include 'inc/panels/comments.html' %}
            {% plugin_left_page object %}
        </div>
        <div class="col col-md-6">
            {% include './inc/lease_card.html' %}
            {% include './inc/ddns_update_card.html' %}
            {% include 'inc/panels/tags.html' %}
            {% plugin_right_page object %}
        </div>
    </div>
    <div class="row">
        <div class="col col-md-12">
            {% plugin_full_width_page object %}
        </div>
    </div>
{% endblock %}

netbox_dhcp/templates/netbox_dhcp/option.html
{% extends 'generic/object.html' %}
{% load i18n %}
{% load netbox_dhcp %}
{% load plugins %}

{% block content %}
    <div class="row">
        <div class="col col-md-6">
            <div class="card">
                <h5 class="card-header">{% trans "Option" %}</h5>
                <table class="table table-hover attr-table">
                    {% if object.description %}
                    <tr>
                        <th scope="row">{% trans "Description" %}</th>
                        <td style="word-break:break-all;">{{ object.description }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Weight" %}</th>
                        <td>{{ object.weight }}</td>
                    </tr>
                    {% endif %}
                    <tr>
                        <th scope="row">{% trans "Address Family" %}</th>
                        <td>{{ object.definition.get_family_display }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Space" %}</th>
                        <td>{{ object.definition.space }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Name" %}</th>
                        <td>{{ object.definition.name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Code" %}</th>
                        <td>{{ object.definition.code }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Data" %}</th>
                        <td>{{ object.data }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Weight" %}</th>
                        <td>{{ object.definition.weight }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "CSV Format" %}</th>
                        <td>{% null_checkmark object.csv_format %}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Send Option" %}</th>
                        <td>{{ object.get_send_option_display }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Definition" %}</th>
                        <td>{{ object.definition|linkify }}</td>
                    </tr>
                </table>
            </div>
            <div class="card">
                <h5 class="card-header">{% trans "Assigned Object" %}</h5>
                <table class="table table-hover attr-table">
                    <tr>
                        <th scope="row">{% trans "Name" %}</th>
                        <td>{{ object.assigned_object|linkify }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Type" %}</th>
                        <td>{{ object.assigned_object_type.name }}</td>
                    </tr>
                </table>
            </div>
            {% include 'inc/panels/custom_fields.html' %}
            {% include 'inc/panels/comments.html' %}
            {% plugin_left_page object %}
        </div>
        <div class="col col-md-6">
            {% include './inc/client_class_card.html' %}
            {% include 'inc/panels/tags.html' %}
            {% plugin_right_page object %}
        </div>
    </div>
    <div class="row">
        <div class="col col-md-12">
            {% plugin_full_width_page object %}
        </div>
    </div>
{% endblock %}

netbox_dhcp/templates/netbox_dhcp/optiondefinition.html
{% extends 'generic/object.html' %}
{% load i18n %}
{% load netbox_dhcp %}
{% load plugins %}

{% block control-buttons %}
{% if object.standard %}
{% else %}
{{ block.super }}
{% endif %}
{% endblock control-buttons %}

{% block content %}
    <div class="row">
        <div class="col col-md-6">
            <div class="card">
                <h5 class="card-header">{% trans "Option Definition" %}</h5>
                <table class="table table-hover attr-table">
                    <tr>
                        <th scope="row">{% trans "Address Family" %}</th>
                        <td>{{ object.get_family_display }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Space" %}</th>
                        <td>{{ object.space }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Name" %}</th>
                        <td>{{ object.name|linkify }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Code" %}</th>
                        <td>{{ object.code }}</td>
                    </tr>
                    {% if object.description %}
                    <tr>
                        <th scope="row">{% trans "Description" %}</th>
                        <td style="word-break:break-all;">{{ object.description }}</td>
                    </tr>
                    {% endif %}
                </table>
            </div>
            {% if object.dhcp_server or object.client_class %}
            <div class="card">
                <h5 class="card-header">{% trans "Parent Object" %}</h5>
                <table class="table table-hover attr-table">
                    {% if object.dhcp_server %}
                        <tr>
                            <th scope="row">{% trans "DHCP Server" %}</th>
                            <td>{{ object.dhcp_server }}</td>
                        </tr>
                    {% endif %}
                    {% if object.client_class %}
                        <tr>
                            <th scope="row">{% trans "Client Class" %}</th>
                            <td>{{ object.client_class }}</td>
                        </tr>
                    {% endif %}
                </table>
            </div>
            {% endif %}
            {% include 'inc/panels/custom_fields.html' %}
            {% include 'inc/panels/comments.html' %}
            {% plugin_left_page object %}
        </div>
        <div class="col col-md-6">
            <div class="card">
                <h5 class="card-header">{% trans "Fields" %}</h5>
                <table class="table table-hover attr-table">
                    <tr>
                        <th scope="row">{% trans "Type" %}</th>
                        <td>{{ object.get_type_display }}</td>
                    </tr>
                    {% if object.type == "record" %}
                    <tr>
                        <th scope="row">{% trans "Record Types" %}</th>
                        <td>{{ object.record_types|display_list }}</td>
                    </tr>
                    {% endif %}
                    <tr>
                        <th scope="row">{% trans "Encapsulate" %}</th>
                        <td>{% null_checkmark object.encapsulate %}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Array" %}</th>
                        <td>{% null_checkmark object.array %}</td>
                    </tr>
                </table>
            </div>
            {% include 'inc/panels/tags.html' %}
            {% plugin_right_page object %}
        </div>
    </div>
    <div class="row">
        <div class="col col-md-12">
            {% plugin_full_width_page object %}
        </div>
    </div>
{% endblock %}