netbox_dhcp/urls.py
from django.urls import include, path

from utilities.urls import get_model_urls

# +
# Import views so the register_model_view is run. This is required for the
# URLs to be set up properly with get_model_urls().
# -
from .views import *  # noqa: F401

app_name = "netbox_dhcp"

urlpatterns = (
    path(
        "clientclasses/",
        include(get_model_urls("netbox_dhcp", "clientclass", detail=False)),
    ),
    path(
        "clientclasses/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "clientclass")),
    ),
    path(
        "ddns/",
        include(get_model_urls("netbox_dhcp", "ddns", detail=False)),
    ),
    path(
        "ddns/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "ddns")),
    ),
    path(
        "hostreservations/",
        include(get_model_urls("netbox_dhcp", "hostreservation", detail=False)),
    ),
    path(
        "hostreservations/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "hostreservation")),
    ),
    path(
        "options/",
        include(get_model_urls("netbox_dhcp", "option", detail=False)),
    ),
    path(
        "options/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "option")),
    ),
    path(
        "optiondefinitions/",
        include(get_model_urls("netbox_dhcp", "optiondefinition", detail=False)),
    ),
    path(
        "optiondefinitions/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "optiondefinition")),
    ),
    path(
        "dhcpclusters/",
        include(get_model_urls("netbox_dhcp", "dhcpcluster", detail=False)),
    ),
    path(
        "dhcpclusters/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "dhcpcluster")),
    ),
    path(
        "dhcpservers/",
        include(get_model_urls("netbox_dhcp", "dhcpserver", detail=False)),
    ),
    path(
        "dhcpservers/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "dhcpserver")),
    ),
    path(
        "pdpools/",
        include(get_model_urls("netbox_dhcp", "pdpool", detail=False)),
    ),
    path(
        "pdpools/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "pdpool")),
    ),
    path(
        "pools/",
        include(get_model_urls("netbox_dhcp", "pool", detail=False)),
    ),
    path(
        "pools/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "pool")),
    ),
    path(
        "sharednetworks/",
        include(get_model_urls("netbox_dhcp", "sharednetwork", detail=False)),
    ),
    path(
        "sharednetworks/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "sharednetwork")),
    ),
    path(
        "subnets/",
        include(get_model_urls("netbox_dhcp", "subnet", detail=False)),
    ),
    path(
        "subnets/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "subnet")),
    ),
)

netbox_dhcp/models/option_definition.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
)

from netbox.models import PrimaryModel
from netbox.search import SearchIndex, register_search
from ipam.choices import IPAddressFamilyChoices

from netbox_dhcp.choices import OptionSpaceChoices, OptionTypeChoices
from netbox_dhcp.fields import ChoiceArrayField

__all__ = (
    "OptionDefinition",
    "OptionDefinitionIndex",
)


class OptionDefinition(PrimaryModel):
    class Meta:
        verbose_name = _("Option Definition")
        verbose_name_plural = _("Option Definitions")

        ordering = (
            "space",
            "code",
            "name",
        )

    clone_fields = ("space",)

    name = models.CharField(
        verbose_name=_("Name"),
        max_length=255,
        blank=False,
        null=False,
    )
    family = models.PositiveIntegerField(
        verbose_name=_("Address Family"),
        choices=IPAddressFamilyChoices,
        blank=False,
        null=False,
        default=IPAddressFamilyChoices.FAMILY_4,
    )
    space = models.CharField(
        verbose_name=_("Space"),
        choices=OptionSpaceChoices,
        blank=False,
        null=False,
        default=OptionSpaceChoices.DHCPV4,
    )
    code = models.PositiveIntegerField(
        verbose_name=_("Code"),
        validators=[
            MinValueValidator(1),
            MaxValueValidator(255),
        ],
        blank=False,
        null=False,
    )
    type = models.CharField(
        verbose_name=_("Type"),
        choices=OptionTypeChoices,
        blank=False,
        null=False,
    )
    record_types = ChoiceArrayField(
        base_field=models.CharField(
            choices=OptionTypeChoices,
        ),
        verbose_name=_("Record Types"),
        blank=True,
        null=True,
    )
    encapsulate = models.CharField(
        verbose_name=_("Encapsulate"),
        blank=True,
        null=True,
    )
    array = models.BooleanField(
        verbose_name=_("Array"),
        null=True,
        blank=True,
    )
    standard = models.BooleanField(
        verbose_name=_("Standard Option Type"),
        blank=False,
        null=False,
        default=False,
    )

    dhcp_server = models.ForeignKey(
        verbose_name=_("DHCP Server"),
        to="DHCPServer",
        on_delete=models.CASCADE,
        related_name="option_definitions",
        blank=True,
        null=True,
    )
    client_class = models.ForeignKey(
        verbose_name=_("Client Class"),
        to="ClientClass",
        on_delete=models.CASCADE,
        related_name="option_definitions",
        blank=True,
        null=True,
    )

    def __str__(self):
        return f"{self.space} {self.name} ({self.code})"

    def get_space_color(self):
        return OptionSpaceChoices.colors.get(self.space)


@register_search
class OptionDefinitionIndex(SearchIndex):
    model = OptionDefinition

    fields = (("name", 100),)

netbox_dhcp/views/dhcp_server.py
from django.utils.translation import gettext_lazy as _

from netbox.views import generic
from utilities.views import register_model_view, ViewTab

from netbox_dhcp.models import (
    DHCPServer,
    Subnet,
    SharedNetwork,
    HostReservation,
    ClientClass,
    Option,
    OptionDefinition,
)
from netbox_dhcp.filtersets import (
    DHCPServerFilterSet,
    SubnetFilterSet,
    SharedNetworkFilterSet,
    HostReservationFilterSet,
    ClientClassFilterSet,
    OptionFilterSet,
    OptionDefinitionFilterSet,
)
from netbox_dhcp.forms import (
    DHCPServerForm,
    DHCPServerFilterForm,
    DHCPServerImportForm,
    DHCPServerBulkEditForm,
)
from netbox_dhcp.tables import (
    DHCPServerTable,
    SubnetTable,
    SharedNetworkTable,
    HostReservationTable,
    ClientClassTable,
    ChildOptionTable,
    OptionDefinitionTable,
)


__all__ = (
    "DHCPServerView",
    "DHCPServerListView",
    "DHCPServerEditView",
    "DHCPServerDeleteView",
    "DHCPServerBulkImportView",
    "DHCPServerBulkEditView",
    "DHCPServerBulkDeleteView",
    "DHCPServerChildSubnetListView",
    "DHCPServerChildSharedNetworkListView",
    "DHCPServerChildHostReservationListView",
    "DHCPServerOptionListView",
    "DHCPServerOptionDefinitionListView",
)


@register_model_view(DHCPServer, "list", path="", detail=False)
class DHCPServerListView(generic.ObjectListView):
    queryset = DHCPServer.objects.all()
    table = DHCPServerTable
    filterset = DHCPServerFilterSet
    filterset_form = DHCPServerFilterForm


@register_model_view(DHCPServer)
class DHCPServerView(generic.ObjectView):
    queryset = DHCPServer.objects.all()


@register_model_view(DHCPServer, "add", detail=False)
@register_model_view(DHCPServer, "edit")
class DHCPServerEditView(generic.ObjectEditView):
    queryset = DHCPServer.objects.all()
    form = DHCPServerForm


@register_model_view(DHCPServer, "delete")
class DHCPServerDeleteView(generic.ObjectDeleteView):
    queryset = DHCPServer.objects.all()


@register_model_view(DHCPServer, "bulk_import", detail=False)
class DHCPServerBulkImportView(generic.BulkImportView):
    queryset = DHCPServer.objects.all()
    model_form = DHCPServerImportForm
    table = DHCPServerTable


@register_model_view(DHCPServer, "bulk_edit", path="edit", detail=False)
class DHCPServerBulkEditView(generic.BulkEditView):
    queryset = DHCPServer.objects.all()
    filterset = DHCPServerFilterSet
    table = DHCPServerTable
    form = DHCPServerBulkEditForm


@register_model_view(DHCPServer, "bulk_delete", path="delete", detail=False)
class DHCPServerBulkDeleteView(generic.BulkDeleteView):
    queryset = DHCPServer.objects.all()
    filterset = DHCPServerFilterSet
    table = DHCPServerTable


@register_model_view(DHCPServer, "child_subnets")
class DHCPServerChildSubnetListView(generic.ObjectChildrenView):
    queryset = DHCPServer.objects.all()
    child_model = Subnet
    table = SubnetTable
    filterset = SubnetFilterSet
    template_name = "netbox_dhcp/dhcpserver/child_subnets.html"

    tab = ViewTab(
        label=_("Subnets"),
        permission="netbox_dhcp.view_subnet",
        badge=lambda obj: obj.child_subnets.count(),
        hide_if_empty=True,
    )

    def get_children(self, request, parent):
        return parent.child_subnets.restrict(request.user, "view")


@register_model_view(DHCPServer, "child_shared_networks")
class DHCPServerChildSharedNetworkListView(generic.ObjectChildrenView):
    queryset = DHCPServer.objects.all()
    child_model = SharedNetwork
    table = SharedNetworkTable
    filterset = SharedNetworkFilterSet
    template_name = "netbox_dhcp/dhcpserver/child_shared_networks.html"

    tab = ViewTab(
        label=_("Shared Networks"),
        permission="netbox_dhcp.view_sharednetwork",
        badge=lambda obj: obj.child_shared_networks.count(),
        hide_if_empty=True,
    )

    def get_children(self, request, parent):
        return parent.child_shared_networks.restrict(request.user, "view")


@register_model_view(DHCPServer, "child_host_reservations")
class DHCPServerChildHostReservationListView(generic.ObjectChildrenView):
    queryset = DHCPServer.objects.all()
    child_model = HostReservation
    table = HostReservationTable
    filterset = HostReservationFilterSet
    template_name = "netbox_dhcp/dhcpserver/child_host_reservations.html"

    tab = ViewTab(
        label=_("Host Reservations"),
        permission="netbox_dhcp.view_hostreservation",
        badge=lambda obj: obj.child_host_reservations.count(),
        hide_if_empty=True,
    )

    def get_children(self, request, parent):
        return parent.child_host_reservations.restrict(request.user, "view")


@register_model_view(DHCPServer, "client_classes")
class DHCPServerClientClassListView(generic.ObjectChildrenView):
    queryset = DHCPServer.objects.all()
    child_model = ClientClass
    table = ClientClassTable
    filterset = ClientClassFilterSet
    template_name = "netbox_dhcp/dhcpserver/client_classes.html"

    tab = ViewTab(
        label=_("Client Classes"),
        permission="netbox_dhcp.view_clientclass",
        badge=lambda obj: obj.client_class_definition_set.count(),
        hide_if_empty=True,
    )

    def get_children(self, request, parent):
        return parent.client_class_definition_set.restrict(request.user, "view")


@register_model_view(DHCPServer, "options")
class DHCPServerOptionListView(generic.ObjectChildrenView):
    queryset = DHCPServer.objects.all()
    child_model = Option
    table = ChildOptionTable
    filterset = OptionFilterSet
    template_name = "netbox_dhcp/dhcpserver/options.html"

    tab = ViewTab(
        label=_("Options"),
        permission="netbox_dhcp.view_option",
        badge=lambda obj: obj.options.count(),
        hide_if_empty=True,
    )

    def get_children(self, request, parent):
        return parent.options.restrict(request.user, "view")


@register_model_view(DHCPServer, "option_definitions")
class DHCPServerOptionDefinitionListView(generic.ObjectChildrenView):
    queryset = DHCPServer.objects.all()
    child_model = OptionDefinition
    table = OptionDefinitionTable
    filterset = OptionDefinitionFilterSet
    template_name = "netbox_dhcp/dhcpserver/option_definitions.html"

    tab = ViewTab(
        label=_("Option Definitions"),
        permission="netbox_dhcp.view_optiondefinition",
        badge=lambda obj: obj.option_definitions.count(),
        hide_if_empty=True,
    )

    def get_children(self, request, parent):
        return parent.option_definitions.restrict(request.user, "view")

netbox_dhcp/views/option.py
from netbox.views import generic
from utilities.views import register_model_view

from netbox_dhcp.models import (
    Option,
    DHCPServer,
    Subnet,
    SharedNetwork,
    Pool,
    PDPool,
    HostReservation,
    ClientClass,
)
from netbox_dhcp.filtersets import OptionFilterSet
from netbox_dhcp.forms import (
    OptionForm,
    OptionFilterForm,
    OptionImportForm,
    OptionBulkEditForm,
)
from netbox_dhcp.tables import OptionTable


__all__ = (
    "OptionView",
    "OptionListView",
    "OptionEditView",
    "OptionDeleteView",
    "OptionBulkImportView",
    "OptionBulkEditView",
    "OptionBulkDeleteView",
)


@register_model_view(Option, "list", path="", detail=False)
class OptionListView(generic.ObjectListView):
    queryset = Option.objects.all()
    table = OptionTable
    actions = {
        "export": {"view"},
        "bulk_import": {"change"},
        "bulk_edit": {"change"},
        "bulk_delete": {"delete"},
    }
    filterset = OptionFilterSet
    filterset_form = OptionFilterForm


@register_model_view(Option)
class OptionView(generic.ObjectView):
    queryset = Option.objects.all()


@register_model_view(Option, "add", detail=False)
@register_model_view(Option, "edit")
class OptionEditView(generic.ObjectEditView):
    queryset = Option.objects.all()
    form = OptionForm

    def alter_object(self, obj, request, url_args, url_kwargs):
        if "dhcp_server" in request.GET:
            try:
                obj.assigned_object = DHCPServer.objects.get(
                    pk=request.GET["dhcp_server"]
                )
            except (ValueError, DHCPServer.DoesNotExist):
                pass

        if "subnet" in request.GET:
            try:
                obj.assigned_object = Subnet.objects.get(pk=request.GET["subnet"])
            except (ValueError, Subnet.DoesNotExist):
                pass

        if "shared_network" in request.GET:
            try:
                obj.assigned_object = SharedNetwork.objects.get(
                    pk=request.GET["shared_network"]
                )
            except (ValueError, SharedNetwork.DoesNotExist):
                pass

        if "pool" in request.GET:
            try:
                obj.assigned_object = Pool.objects.get(pk=request.GET["pool"])
            except (ValueError, Pool.DoesNotExist):
                pass

        if "pd_pool" in request.GET:
            try:
                obj.assigned_object = PDPool.objects.get(pk=request.GET["pd_pool"])
            except (ValueError, PDPool.DoesNotExist):
                pass

        if "host_reservation" in request.GET:
            try:
                obj.assigned_object = HostReservation.objects.get(
                    pk=request.GET["host_reservation"]
                )
            except (ValueError, HostReservation.DoesNotExist):
                pass

        if "client_class" in request.GET:
            try:
                obj.assigned_object = ClientClass.objects.get(
                    pk=request.GET["client_class"]
                )
            except (ValueError, ClientClass.DoesNotExist):
                pass

        return obj

    def get_extra_addanother_params(self, request):
        for parameter in (
            "dhcp_server",
            "subnet",
            "shared_network",
            "pool",
            "pd_pool",
            "host_reservation",
            "client_class",
        ):
            if parameter in request.GET:
                return {parameter: request.GET[parameter]}

        return {}


@register_model_view(Option, "delete")
class OptionDeleteView(generic.ObjectDeleteView):
    queryset = Option.objects.all()


@register_model_view(Option, "bulk_import", detail=False)
class OptionBulkImportView(generic.BulkImportView):
    queryset = Option.objects.all()
    model_form = OptionImportForm
    table = OptionTable


@register_model_view(Option, "bulk_edit", path="edit", detail=False)
class OptionBulkEditView(generic.BulkEditView):
    queryset = Option.objects.all()
    filterset = OptionFilterSet
    table = OptionTable
    form = OptionBulkEditForm


@register_model_view(Option, "bulk_delete", path="delete", detail=False)
class OptionBulkDeleteView(generic.BulkDeleteView):
    queryset = Option.objects.all()
    filterset = OptionFilterSet
    table = OptionTable

netbox_dhcp/templates/netbox_dhcp/dhcpserver/base.html
{% extends 'generic/object.html' %}
{% load perms %}
{% load i18n %}


{% block extra_controls %}
    {% if perms.netbox_dhcp.add_optiondefinition or perms.netbox_dhcp.add_option or perms.netbox_dhcp.add_hostreservation or perms.netbox_dhcp.add_sharednetwork or perms.netbox_dhcp.add_subnet or perms.netbox_dhcp.add_clientclass %}
        <div class="dropdown">
            <button id="add-objects" type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="mdi mdi-plus-thick" aria-hidden="true"></i> {% trans "Add Object" %}
            </button>
            <ul class="dropdown-menu" aria-labeled-by="add-objects">
                {% if perms.netbox_dhcp.add_optiondefinition %}
                    <li><a class="dropdown-item" href="{% url 'plugins:netbox_dhcp:optiondefinition_add' %}?dhcp_server={{ object.pk }}&return_url={% url 'plugins:netbox_dhcp:dhcpserver_option_definitions' pk=object.pk %}">{% trans "Option Definition" %}</a></li>
                {% endif %}
                {% if perms.netbox_dhcp.add_option %}
                    <li><a class="dropdown-item" href="{% url 'plugins:netbox_dhcp:option_add' %}?dhcp_server={{ object.pk }}&return_url={% url 'plugins:netbox_dhcp:dhcpserver_options' pk=object.pk %}">{% trans "Option" %}</a></li>
                {% endif %}
                {% if perms.netbox_dhcp.add_hostreservation %}
                    <li><a class="dropdown-item" href="{% url 'plugins:netbox_dhcp:hostreservation_add' %}?dhcp_server={{ object.pk }}&return_url={% url 'plugins:netbox_dhcp:dhcpserver_child_host_reservations' pk=object.pk %}">{% trans "Host Reservation" %}</a></li>
                {% endif %}
                {% if perms.netbox_dhcp.add_sharednetwork %}
                    <li><a class="dropdown-item" href="{% url 'plugins:netbox_dhcp:sharednetwork_add' %}?dhcp_server={{ object.pk }}&return_url={% url 'plugins:netbox_dhcp:dhcpserver_child_shared_networks' pk=object.pk %}">{% trans "Shared Network" %}</a></li>
                {% endif %}
                {% if perms.netbox_dhcp.add_subnet %}
                    <li><a class="dropdown-item" href="{% url 'plugins:netbox_dhcp:subnet_add' %}?dhcp_server={{ object.pk }}&return_url={% url 'plugins:netbox_dhcp:dhcpserver_child_subnets' pk=object.pk %}">{% trans "Subnet" %}</a></li>
                {% endif %}
                {% if perms.netbox_dhcp.add_clientclass %}
                    <li><a class="dropdown-item" href="{% url 'plugins:netbox_dhcp:clientclass_add' %}?dhcp_server={{ object.pk }}&return_url={% url 'plugins:netbox_dhcp:dhcpserver_client_classes' pk=object.pk %}">{% trans "Client Class" %}</a></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

netbox_dhcp/templates/netbox_dhcp/dhcpserver/child_client_classes.html
{% extends './base.html' %}
{% load helpers %}

{% block content %}
    {% include 'inc/table_controls_htmx.html' with table_modal="ClientClassTable_config" %}
    {% include '../inc/client_class_table.html' %}
{% endblock %}

{% block modals %}
    {{ block.super }}
    {% table_config_form table %}
{% endblock modals %}

netbox_dhcp/templates/netbox_dhcp/dhcpserver/child_host_reservations.html
{% extends './base.html' %}
{% load helpers %}

{% block content %}
    {% include 'inc/table_controls_htmx.html' with table_modal="HostReservationTable_config" %}
    {% include '../inc/object_table.html' %}
{% endblock %}

{% block modals %}
    {{ block.super }}
    {% table_config_form table %}
{% endblock modals %}

netbox_dhcp/templates/netbox_dhcp/dhcpserver/child_shared_networks.html
{% extends './base.html' %}
{% load helpers %}

{% block content %}
    {% include 'inc/table_controls_htmx.html' with table_modal="SharedNetworkTable_config" %}
    {% include '../inc/object_table.html' %}
{% endblock %}

{% block modals %}
    {{ block.super }}
    {% table_config_form table %}
{% endblock modals %}

netbox_dhcp/templates/netbox_dhcp/dhcpserver/child_subnets.html
{% extends './base.html' %}
{% load helpers %}

{% block content %}
    {% include 'inc/table_controls_htmx.html' with table_modal="SubnetTable_config" %}
    {% include '../inc/object_table.html' %}
{% endblock %}

{% block modals %}
    {{ block.super }}
    {% table_config_form table %}
{% endblock modals %}

netbox_dhcp/templates/netbox_dhcp/dhcpserver/client_classes.html
{% extends './base.html' %}
{% load helpers %}

{% block content %}
    {% include 'inc/table_controls_htmx.html' with table_modal="ClientClassTable_config" %}
    {% include '../inc/object_table.html' %}
{% endblock %}

{% block modals %}
    {{ block.super }}
    {% table_config_form table %}
{% endblock modals %}

netbox_dhcp/templates/netbox_dhcp/dhcpserver/option_definitions.html
{% extends './base.html' %}
{% load helpers %}

{% block content %}
    {% include 'inc/table_controls_htmx.html' with table_modal="OptionDefinitionTable_config" %}
    {% include '../inc/object_table.html' %}
{% endblock %}

{% block modals %}
    {{ block.super }}
    {% table_config_form table %}
{% endblock modals %}

netbox_dhcp/templates/netbox_dhcp/dhcpserver/options.html
{% extends './base.html' %}
{% load helpers %}

{% block content %}
    {% include 'inc/table_controls_htmx.html' with table_modal="ChildOptionTable_config" %}
    {% include '../inc/object_table.html' %}
{% endblock %}

{% block modals %}
    {{ block.super }}
    {% table_config_form table %}
{% endblock modals %}