netbox_dhcp/urls.py
from django.urls import include, path

from utilities.urls import get_model_urls

# +
# Import views so the register_model_view is run. This is required for the
# URLs to be set up properly with get_model_urls().
# -
from .views import *  # noqa: F401

app_name = "netbox_dhcp"

urlpatterns = (
    path(
        "clientclasses/",
        include(get_model_urls("netbox_dhcp", "clientclass", detail=False)),
    ),
    path(
        "clientclasses/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "clientclass")),
    ),
    path(
        "ddns/",
        include(get_model_urls("netbox_dhcp", "ddns", detail=False)),
    ),
    path(
        "ddns/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "ddns")),
    ),
    path(
        "hostreservations/",
        include(get_model_urls("netbox_dhcp", "hostreservation", detail=False)),
    ),
    path(
        "hostreservations/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "hostreservation")),
    ),
    path(
        "options/",
        include(get_model_urls("netbox_dhcp", "option", detail=False)),
    ),
    path(
        "options/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "option")),
    ),
    path(
        "optiondefinitions/",
        include(get_model_urls("netbox_dhcp", "optiondefinition", detail=False)),
    ),
    path(
        "optiondefinitions/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "optiondefinition")),
    ),
    path(
        "dhcpclusters/",
        include(get_model_urls("netbox_dhcp", "dhcpcluster", detail=False)),
    ),
    path(
        "dhcpclusters/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "dhcpcluster")),
    ),
    path(
        "dhcpservers/",
        include(get_model_urls("netbox_dhcp", "dhcpserver", detail=False)),
    ),
    path(
        "dhcpservers/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "dhcpserver")),
    ),
    path(
        "pdpools/",
        include(get_model_urls("netbox_dhcp", "pdpool", detail=False)),
    ),
    path(
        "pdpools/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "pdpool")),
    ),
    path(
        "pools/",
        include(get_model_urls("netbox_dhcp", "pool", detail=False)),
    ),
    path(
        "pools/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "pool")),
    ),
    path(
        "sharednetworks/",
        include(get_model_urls("netbox_dhcp", "sharednetwork", detail=False)),
    ),
    path(
        "sharednetworks/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "sharednetwork")),
    ),
    path(
        "subnets/",
        include(get_model_urls("netbox_dhcp", "subnet", detail=False)),
    ),
    path(
        "subnets/<int:pk>/",
        include(get_model_urls("netbox_dhcp", "subnet")),
    ),
)

netbox_dhcp/models/mixins.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from netbox_dhcp.choices import (
    DDNSReplaceClientNameChoices,
    DDNSConflictResolutionModeChoices,
    AllocatorTypeChoices,
    PDAllocatorTypeChoices,
)

__all__ = (
    "NetBoxDHCPModelMixin",
    "BOOTPModelMixin",
    "ClientClassModelMixin",
    "EvaluateClientClassModelMixin",
    "LifetimeModelMixin",
    "OfferLifetimeModelMixin",
    "DDNSUpdateModelMixin",
    "LeaseModelMixin",
    "NetworkModelMixin",
)


class NetBoxDHCPModelMixin(models.Model):
    FIELDS = [
        "name",
        "description",
    ]

    class Meta:
        abstract = True

    name = models.CharField(
        verbose_name=_("Name"),
        unique=True,
        max_length=255,
        db_collation="natural_sort",
    )

    def __str__(self):
        return str(self.name)


class BOOTPModelMixin(models.Model):
    FIELDS = [
        "next_server",
        "server_hostname",
        "boot_file_name",
    ]

    class Meta:
        abstract = True

    next_server = models.CharField(
        verbose_name=_("Next Server"),
        blank=True,
        null=True,
        max_length=15,
    )
    server_hostname = models.CharField(
        verbose_name=_("Server Hostname"),
        blank=True,
        null=True,
        max_length=64,
    )
    boot_file_name = models.CharField(
        verbose_name=_("Boot File Name"),
        blank=True,
        null=True,
        max_length=128,
    )


class ClientClassModelMixin(models.Model):
    class Meta:
        abstract = True

    client_classes = models.ManyToManyField(
        verbose_name=_("Client Classes"),
        to="ClientClass",
        related_name="%(class)s_set",
        blank=True,
    )


class EvaluateClientClassModelMixin(models.Model):
    class Meta:
        abstract = True

    evaluate_additional_classes = models.ManyToManyField(
        verbose_name=_("Evaluate Additional Classes"),
        to="ClientClass",
        related_name="evaluate_%(class)s_set",
        blank=True,
    )


class ValidLifetimeModelMixin(models.Model):
    class Meta:
        abstract = True

    valid_lifetime = models.PositiveIntegerField(
        verbose_name=_("Valid Lifetime"),
        null=True,
        blank=True,
    )
    min_valid_lifetime = models.PositiveIntegerField(
        verbose_name=_("Minimum Valid Lifetime"),
        null=True,
        blank=True,
    )
    max_valid_lifetime = models.PositiveIntegerField(
        verbose_name=_("Maximum Valid Lifetime"),
        null=True,
        blank=True,
    )


class PreferredLifetimeModelMixin(models.Model):
    class Meta:
        abstract = True

    preferred_lifetime = models.PositiveIntegerField(
        verbose_name=_("Preferred Lifetime"),
        null=True,
        blank=True,
    )
    min_preferred_lifetime = models.PositiveIntegerField(
        verbose_name=_("Minimum Preferred Lifetime"),
        null=True,
        blank=True,
    )
    max_preferred_lifetime = models.PositiveIntegerField(
        verbose_name=_("Maximum Preferred Lifetime"),
        null=True,
        blank=True,
    )


class OfferLifetimeModelMixin(models.Model):
    class Meta:
        abstract = True

    offer_lifetime = models.PositiveIntegerField(
        verbose_name=_("Offer Lifetime"),
        null=True,
        blank=True,
    )


class LifetimeModelMixin(
    ValidLifetimeModelMixin,
    PreferredLifetimeModelMixin,
    OfferLifetimeModelMixin,
):
    class Meta:
        abstract = True


class DDNSUpdateModelMixin(models.Model):
    class Meta:
        abstract = True

    ddns_send_updates = models.BooleanField(
        verbose_name=_("Send DDNS updates"),
        null=True,
        blank=True,
    )
    ddns_override_no_update = models.BooleanField(
        verbose_name=_("Override client 'no update' flag"),
        null=True,
        blank=True,
    )
    ddns_override_client_update = models.BooleanField(
        verbose_name=_("Override client delegation flags"),
        null=True,
        blank=True,
    )
    ddns_replace_client_name = models.CharField(
        verbose_name=_("Replace client name"),
        choices=DDNSReplaceClientNameChoices,
        blank=True,
        null=True,
    )
    ddns_generated_prefix = models.CharField(
        verbose_name=_("Generated Prefix"),
        blank=True,
        null=True,
    )
    ddns_qualifying_suffix = models.CharField(
        verbose_name=_("Qualifying Suffix"),
        blank=True,
        null=True,
    )
    ddns_update_on_renew = models.BooleanField(
        verbose_name=_("Update DDNS on renew"),
        null=True,
        blank=True,
    )
    ddns_conflict_resolution_mode = models.CharField(
        verbose_name=_("Conflict Resolution Mode"),
        choices=DDNSConflictResolutionModeChoices,
        blank=True,
        null=True,
    )
    ddns_ttl_percent = models.DecimalField(
        verbose_name=_("TTL Percent"),
        max_digits=4,
        decimal_places=3,
        null=True,
        blank=True,
    )
    ddns_ttl = models.PositiveIntegerField(
        verbose_name=_("TTL"),
        null=True,
        blank=True,
    )
    ddns_ttl_min = models.PositiveIntegerField(
        verbose_name=_("Minimum TTL"),
        null=True,
        blank=True,
    )
    ddns_ttl_max = models.PositiveIntegerField(
        verbose_name=_("Maximum TTL"),
        null=True,
        blank=True,
    )
    hostname_char_set = models.CharField(
        verbose_name=_("Allowed Characters in Host Names"),
        max_length=255,
        blank=True,
    )
    hostname_char_replacement = models.CharField(
        verbose_name=_("Replacement Character for Invalid Host Names"),
        max_length=255,
        blank=True,
    )

    def get_ddns_replace_client_name_color(self):
        return DDNSReplaceClientNameChoices.colors.get(self.ddns_replace_client_name)

    def get_ddns_conflict_resolution_mode_color(self):
        return DDNSConflictResolutionModeChoices.colors.get(
            self.ddns_conflict_resolution_mode
        )


class LeaseModelMixin(models.Model):
    class Meta:
        abstract = True

    renew_timer = models.PositiveIntegerField(
        verbose_name=_("Renew Timer"),
        null=True,
        blank=True,
    )
    rebind_timer = models.PositiveIntegerField(
        verbose_name=_("Rebind Timer"),
        null=True,
        blank=True,
    )
    match_client_id = models.BooleanField(
        verbose_name=_("Match Client ID"),
        null=True,
        blank=True,
    )
    authoritative = models.BooleanField(
        verbose_name=_("Authoritative"),
        null=True,
        blank=True,
    )
    reservations_global = models.BooleanField(
        verbose_name=_("Global reservations"),
        null=True,
        blank=True,
    )
    reservations_out_of_pool = models.BooleanField(
        verbose_name=_("Out-of-pool reservations"),
        null=True,
        blank=True,
    )
    reservations_in_subnet = models.BooleanField(
        verbose_name=_("In-subnet reservations"),
        null=True,
        blank=True,
    )
    calculate_tee_times = models.BooleanField(
        verbose_name=_("Calculate T times"),
        null=True,
        blank=True,
    )
    t1_percent = models.DecimalField(
        verbose_name=_("T1 Percent"),
        max_digits=4,
        decimal_places=3,
        null=True,
        blank=True,
    )
    t2_percent = models.DecimalField(
        verbose_name=_("T2 Percent"),
        max_digits=4,
        decimal_places=3,
        null=True,
        blank=True,
    )
    cache_threshold = models.DecimalField(
        verbose_name=_("Cache Threshold"),
        max_digits=3,
        decimal_places=2,
        null=True,
        blank=True,
    )
    cache_max_age = models.PositiveIntegerField(
        verbose_name=_("Maximum Cache Age"),
        null=True,
        blank=True,
    )
    adaptive_lease_time_threshold = models.DecimalField(
        verbose_name=_("Adaptive Lease Time Threshold"),
        max_digits=3,
        decimal_places=2,
        null=True,
        blank=True,
    )
    store_extended_info = models.BooleanField(
        verbose_name=_("Store Extended Info"),
        null=True,
        blank=True,
    )
    allocator = models.CharField(
        verbose_name=_("Allocator"),
        choices=AllocatorTypeChoices,
        blank=True,
        null=True,
    )
    pd_allocator = models.CharField(
        verbose_name=_("Prefix Delegation Allocator"),
        choices=PDAllocatorTypeChoices,
        blank=True,
        null=True,
    )

    def get_allocator_color(self):
        return AllocatorTypeChoices.colors.get(self.allocator)

    def get_pd_allocator_color(self):
        return PDAllocatorTypeChoices.colors.get(self.pd_allocator)


class NetworkModelMixin(models.Model):
    class Meta:
        abstract = True

    server_interfaces = models.ManyToManyField(
        verbose_name=_("Server Interfaces"),
        to="DHCPServerInterface",
        blank=True,
    )
    relay = models.CharField(
        verbose_name=_("Relay IP Addresses"),
        max_length=255,
        blank=True,
        null=True,
    )
    interface_id = models.CharField(
        verbose_name=_("Interface ID"),
        max_length=255,
        blank=True,
        null=True,
    )
    rapid_commit = models.BooleanField(
        verbose_name=_("Rapid Commit"),
        null=True,
        blank=True,
    )

netbox_dhcp/templates/netbox_dhcp/inc/bootp_card.html
{% load i18n %}

{% if object.family is none or object.family == 4 %}
<div class="card">
    <h5 class="card-header">{% trans "BOOTP" %}</h5>
    <table class="table table-hover attr-table">
        <tr>
            <th scope="row">{% trans "Next Server" %}</th>
            <td>{{ object.next_server|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Server Hostname" %}</th>
            <td>{{ object.server_hostname|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Boot File Name" %}</th>
            <td>{{ object.boot_file_name|placeholder }}</td>
        </tr>
    </table>
</div>
{% endif %}

netbox_dhcp/templates/netbox_dhcp/inc/client_class_card.html
{% load i18n %}
{% load netbox_dhcp %}

<div class="card">
    <h5 class="card-header">{% trans "Client Classes" %}</h5>
    <table class="table table-hover attr-table">
        <tr>
            <th scope="row">{% trans "Client Classes" %}</th>
            {% if object.client_classes.exists %}
            <td>
                <table>
                    {% for class in object.client_classes.all %}
                        <tr><td>{{ class|linkify|placeholder }}</td></tr>
                    {% endfor %}
                </table>
            </td>
            {% else %}
            <td>{{ ''|placeholder }}</td>
            {% endif %}
        </tr>
        <tr>
            <th scope="row">{% trans "Evaluate Additional Classes" %}</th>
            {% if object.evaluate_additional_classes.exists %}
            <td>
                <table>
                    {% for class in object.evaluate_additional_classes.all %}
                        <tr><th/><td>{{ class|linkify|placeholder }}</td></tr>
                    {% endfor %}
                </table>
            </td>
            {% else %}
            <td>{{ ''|placeholder }}</td>
            {% endif %}
        </tr>
    </table>
</div>

netbox_dhcp/templates/netbox_dhcp/inc/client_class_fields.html
{% load i18n %}

<tr>
    <th scope="row">{% trans "Client Class" %}</th>
    <td>{{ object.client_class|linkify|placeholder }}</td>
</tr>
<tr>
    <th scope="row">{% trans "Require Client Classes" %}</th>
    <td>
        <table>
            {% for class in object.require_client_classes.all %}
                <tr><td>{{ class|linkify|placeholder }}</td></tr>
            {% endfor %}
        </table>
    </td>
</tr>
<tr>
    <th scope="row">{% trans "Evaluate Additional Classes" %}</th>
    <td>
        <table>
            {% for class in object.evaluate_additional_classes.all %}
                <tr><td>{{ class|linkify|placeholder }}</td></tr>
            {% endfor %}
        </table>
    </td>
</tr>

netbox_dhcp/templates/netbox_dhcp/inc/client_class_table.html
{% load helpers %}
{% load render_table from django_tables2 %}
{% load perms %}
{% load i18n %}

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="return_url" value="{% if return_url %}{{ return_url }}{% else %}{{ request.path }}{% if request.GET %}?{{ request.GET.urlencode }}{% endif %}{% endif %}" />

    <div class="card">
        <div class="htmx-container table-responsive" id="object_list">
            {% include 'htmx/table.html' %}
        </div>
    </div>

    {% if perms.netbox_dhcp.change_clientclass or perms.netbox_dhcp.delete_clientclass %}
        {% with bulk_edit_url="plugins:netbox_dhcp:clientclass_bulk_edit" bulk_delete_url="plugins:netbox_dhcp:clientclass_bulk_delete" %}
             <div class="noprint bulk-buttons">
                   <div class="bulk-button-group">
                       {% block bulk_buttons %}{% endblock %}
                       {% if bulk_edit_url and perms.netbox_dhcp.change_clientclass %}
                           <button type="submit" name="_edit" formaction="{% url bulk_edit_url %}{% if request.GET %}?{{ request.GET.urlencode }}{% endif %}" class="btn btn-warning">
                               <i class="mdi mdi-pencil" aria-hidden="true"></i> {% trans "Edit Selected" %}
                           </button>
                       {% endif %}
                       {% if bulk_delete_url and perms.netbox_dhcp.delete_clientclass %}
                           <button type="submit" name="_delete" formaction="{% url bulk_delete_url %}{% if request.GET %}?{{ request.GET.urlencode }}{% endif %}" class="btn btn-danger">
                               <i class="mdi mdi-trash-can-outline" aria-hidden="true"></i> {% trans "Delete Selected" %}
                           </button>
                       {% endif %}
                   </div>
             </div>
        {% endwith %}
    {% endif %}
 </form>

netbox_dhcp/templates/netbox_dhcp/inc/ddns_update_card.html
{% load i18n %}
{% load netbox_dhcp %}

{% if object.ddns_send_updates %}
<div class="card">
    <h5 class="card-header">{% trans "Dynamic DNS Update" %}</h5>
    <table class="table table-hover attr-table">
        <tr>
            <th scope="row">{% trans "Send DDNS updates" %}</th>
            <td>{% null_checkmark object.ddns_send_updates %}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Override client 'no update' flag" %}</th>
            <td>{% null_checkmark object.ddns_override_no_update %}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Override client delegation flags" %}</th>
            <td>{% null_checkmark object.ddns_override_client_update %}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Replace Client Name" %}</th>
            <td>{% badge object.get_ddns_replace_client_name_display bg_color=object.get_ddns_replace_client_name_color %}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Generated Prefix" %}</th>
            <td>{{ object.ddns_generated_prefix|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Qualifying Suffix" %}</th>
            <td>{{ object.ddns_qualifying_suffix|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Update DDNS on renew" %}</th>
            <td>{% null_checkmark object.ddns_update_on_renew %}</td>
        </tr>
        <th scope="row">{% trans "Conflict Resolution Mode" %}</th>
            <td>{% badge object.get_ddns_conflict_resolution_mode_display bg_color=object.get_ddns_conflict_resolution_mode_color %}</td>
        <tr>
            <th scope="row">{% trans "TTL Percent" %}</th>
            <td>{{ object.ddns_ttl_percent|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "TTL" %}</th>
            <td>{{ object.ddns_ttl|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Minimum TTL" %}</th>
            <td>{{ object.ttl_min|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Maximum TTL" %}</th>
            <td>{{ object.ddns_ttl_max|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Allowed Characters in Host Names" %}</th>
            <td>{{ object.hostname_char_set }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Replacement Character for Invalid Host Names" %}</th>
            <td>{{ object.hostname_char_replacement }}</td>
        </tr>
    </table>
</div>
{% endif %}

netbox_dhcp/templates/netbox_dhcp/inc/lease_card.html
{% load i18n %}
{% load netbox_dhcp %}

<div class="card">
    <h5 class="card-header">{% trans "Lease" %}</h5>
    <table class="table table-hover attr-table">
        <tr>
            <th scope="row">{% trans "Allocator" %}</th>
            <td>{% badge object.get_allocator_display bg_color=object.get_allocator_color %}</td>
        </tr>
        {% if object.allocator == "flq" %}
        <tr>
            <th scope="row">{% trans "Adaptive Lease Time Threshold" %}</th>
            <td>{{ object.adaptive_lease_time_threshold|placeholder }}</td>
        </tr>
        {% endif %}
        {% if object.family is none or object.family == 6 %}
        <tr>
            <th scope="row">{% trans "Prefix Delegation Allocator" %}</th>
            <td>{% badge object.get_pd_allocator_display bg_color=object.get_pd_allocator_color %}</td>
        </tr>
        {% endif %}
        {% if object.calculate_tee_times %}
        <tr>
            <th scope="row">{% trans "Calculate T times" %}</th>
            <td>{% null_checkmark object.calculate_tee_times %}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "T1 Percent" %}</th>
            <td>{{ object.t1_percent|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "T2 Percent" %}</th>
            <td>{{ object.t2_percent|placeholder }}</td>
        </tr>
        {% else %}
        <tr>
            <th scope="row">{% trans "Renew Timer" %}</th>
            <td>{{ object.renew_timer|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Rebind Timer" %}</th>
            <td>{{ object.rebind_timer|placeholder }}</td>
        </tr>
        {% endif %}
        {% if object.family is none or object.family == 4 %}
        <tr>
            <th scope="row">{% trans "Match Client ID" %}</th>
            <td>{% null_checkmark object.match_client_id %}</td>
        </tr>
        {% endif %}
        <tr>
            <th scope="row">{% trans "Store Extended Info" %}</th>
            <td>{% null_checkmark object.store_extended_info %}</td>
        </tr>
        {% if object.family is none or object.family == 4 %}
        <tr>
            <th scope="row">{% trans "Authoritative" %}</th>
            <td>{% null_checkmark object.authoritative %}</td>
        </tr>
        {% endif %}
        <tr>
            <th scope="row">{% trans "Global reservations" %}</th>
            <td>{% null_checkmark object.reservations_global %}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Out-of-pool reservations" %}</th>
            <td>{% null_checkmark object.reservations_out_of_pool %}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "In-subnet reservations" %}</th>
            <td>{% null_checkmark object.reservations_in_subnet %}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Cache Threshold" %}</th>
            <td>{{ object.cache_threshold|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Maximum Cache Age" %}</th>
            <td>{{ object.cache_max_age|placeholder }}</td>
        </tr>
    </table>
</div>

netbox_dhcp/templates/netbox_dhcp/inc/lifetime_card.html
{% load i18n %}

<div class="card">
    <h5 class="card-header">{% trans "Lifetimes" %}</h5>
    <table class="table table-hover attr-table">
        {% if object.family is none or object.family == 4 %}
        <tr>
            <th scope="row">{% trans "Offer Lifetime" %}</th>
            <td>{{ object.offer_lifetime|placeholder }}</td>
        </tr>
        {% endif %}
        <tr>
            <th scope="row">{% trans "Valid Lifetime" %}</th>
            <td>{{ object.valid_lifetime|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Minimum Valid Lifetime" %}</th>
            <td>{{ object.min_valid_lifetime|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Maximum Valid Lifetime" %}</th>
            <td>{{ object.max_valid_lifetime|placeholder }}</td>
        </tr>
        {% if object.family is none or object.family == 6 %}
        <tr>
            <th scope="row">{% trans "Preferred Lifetime" %}</th>
            <td>{{ object.preferred_lifetime|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Minimum Preferred Lifetime" %}</th>
            <td>{{ object.min_preferred_lifetime|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Maximum Preferred Lifetime" %}</th>
            <td>{{ object.max_preferred_lifetime|placeholder }}</td>
        </tr>
        {% endif %}
    </table>
</div>

netbox_dhcp/templates/netbox_dhcp/inc/name_description_fields.html
{% load i18n %}

<tr>
    <th scope="row">{% trans "Name" %}</th>
    <td>{{ object.name }}</td>
</tr>
{% if object.description %}
<tr>
    <th scope="row">{% trans "Description" %}</th>
    <td style="word-break:break-all;">{{ object.description }}</td>
</tr>
{% endif %}

netbox_dhcp/templates/netbox_dhcp/inc/network_card.html
{% load i18n %}
{% load netbox_dhcp %}

<div class="card">
    <h5 class="card-header">{% trans "Network" %}</h5>
    <table class="table table-hover attr-table">
        <tr>
            <th scope="row">{% trans "Interfaces" %}</th>
            <td>
                <table>
                    {% for interface in object.server_interfaces.all %}
                        <tr><td>{{ interface }}</td></tr>
                    {% endfor %}
                </table>
            </td>
        </tr>
        <tr>
            <th scope="row">{% trans "Relay" %}</th>
            <td>{{ object.relay|placeholder }}</td>
        </tr>
        {% if object.family is none or object.family == 6 %}
        <tr>
            <th scope="row">{% trans "Interface ID" %}</th>
            <td>{{ object.interface_id|placeholder }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Rapid Commit" %}</th>
            <td>{% null_checkmark object.rapid_commit %}</td>
        </tr>
        {% endif %}
    </table>
</div>

netbox_dhcp/templates/netbox_dhcp/inc/null_checkmark.html
{% if value is None %}
  <span class="text-muted">&mdash;</span>
{% elif value %}
  <i class="mdi mdi-check-bold text-success" title="{{ true_label }}"></i>
{% else %}
  <i class="mdi mdi-close-thick text-danger" title="{{ false_label }}"></i>
{% endif %}

netbox_dhcp/templates/netbox_dhcp/inc/object_table.html
{% load helpers %}
{% load buttons %}

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="return_url" value="{% if return_url %}{{ return_url }}{% else %}{{ request.path }}{% if request.GET %}?{{ request.GET.urlencode }}{% endif %}{% endif %}" />

    <div class="card">
        <div class="htmx-container table-responsive" id="object_list">
            {% include 'htmx/table.html' %}
        </div>
    </div>

    {% action_buttons actions model multi=True %}
 </form>